#!/usr/bin/env python3
"""Embed standard theme GIFs as LVGL C arrays for the VIEWE sketch.

Writes:
  firmware/viewe/cursor_agent_beacon/theme_gifs.h
  firmware/viewe/cursor_agent_beacon/theme_gifs.c

ponytail: embed ~100KB of GIF bytes in flash (no FAT upload). Ceiling: theme
swap needs a reflash; upgrade path is FFat + LV_USE_FS_* file sources.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from cursor_agent_beacon.theme import load_theme  # noqa: E402

OUT_DIR = ROOT / "firmware" / "viewe" / "cursor_agent_beacon"
REQUIRED_STATES = (
    "idle",
    "waiting",
    "thinking",
    "running_shell",
    "running_mcp",
    "success",
    "error",
    "stop",
)


def c_ident(stem: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]", "_", stem)
    if cleaned[0].isdigit():
        cleaned = f"g_{cleaned}"
    return cleaned


def emit_array(name: str, data: bytes) -> str:
    lines = [f"static const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{"]
    chunk = 16
    for i in range(0, len(data), chunk):
        part = ", ".join(f"0x{b:02X}" for b in data[i : i + chunk])
        suffix = "," if i + chunk < len(data) else ""
        lines.append(f"    {part}{suffix}")
    lines.append("};")
    lines.append("")
    lines.append(f"const lv_img_dsc_t {name} = {{")
    lines.append("    .header.always_zero = 0,")
    lines.append("    .header.w = 480,")
    lines.append("    .header.h = 480,")
    lines.append("    .header.cf = LV_IMG_CF_RAW,")
    lines.append(f"    .data_size = sizeof({name}_map),")
    lines.append(f"    .data = {name}_map,")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Embed theme GIFs as LVGL C arrays")
    parser.add_argument("--theme", default="standard")
    parser.add_argument("--output", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    theme = load_theme(args.theme, ROOT / "themes")
    missing = [s for s in REQUIRED_STATES if s not in theme.animations]
    assert not missing, f"theme missing states: {missing}"

    # One C symbol per unique GIF path (idle→sleeping, stop→stop, …).
    path_to_symbol: dict[Path, str] = {}
    state_to_symbol: dict[str, str] = {}
    for state, anim in theme.animations.items():
        path = anim.path.resolve()
        assert path.is_file(), f"missing GIF: {path}"
        if path not in path_to_symbol:
            path_to_symbol[path] = f"beacon_gif_{c_ident(path.stem)}"
        state_to_symbol[state] = path_to_symbol[path]

    args.output.mkdir(parents=True, exist_ok=True)
    header = args.output / "theme_gifs.h"
    source = args.output / "theme_gifs.c"

    header.write_text(
        "\n".join(
            [
                "/* Auto-generated by scripts/embed_theme_gifs.py — do not edit. */",
                "#pragma once",
                "",
                "#include <lvgl.h>",
                "",
                "#ifdef __cplusplus",
                'extern "C" {',
                "#endif",
                "",
                "const lv_img_dsc_t *beacon_gif_for_state(const char *state);",
                "",
                "#ifdef __cplusplus",
                "}",
                "#endif",
                "",
            ]
        ),
        encoding="utf-8",
    )

    parts = [
        "/* Auto-generated by scripts/embed_theme_gifs.py — do not edit. */",
        '#include "theme_gifs.h"',
        "",
        "#include <string.h>",
        "",
    ]
    for path, symbol in path_to_symbol.items():
        parts.append(emit_array(symbol, path.read_bytes()))
        print(f"  {path.name} -> {symbol} ({path.stat().st_size} bytes)")

    parts.append("const lv_img_dsc_t *beacon_gif_for_state(const char *state)")
    parts.append("{")
    parts.append("    if (state == NULL || state[0] == '\\0') {")
    parts.append(f"        return &{state_to_symbol['idle']};")
    parts.append("    }")
    for state in REQUIRED_STATES:
        parts.append(f'    if (strcmp(state, "{state}") == 0) {{')
        parts.append(f"        return &{state_to_symbol[state]};")
        parts.append("    }")
    parts.append(f"    return &{state_to_symbol['idle']};")
    parts.append("}")
    parts.append("")

    source.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {header}")
    print(f"Wrote {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
